#pragma once

#include <iostream>

//#define __BASICS__
//#define __MULTIPLY_BY_TWO__
//#define __FUNCTIONS__
//#define __FORWARD_DECLARATIONS__
//#define __PRE_PROCESSOR_DIRECTIVES__
//#define __HEADER_GUARDS__
//#define __INTEGRAL_TYPES__
//#define __LITERALS__
//#define __CONSTANTS__
//#define __BIT_MANIPULATION__
//#define __BIT_WISE_OPERATORS__
//#define __BIT_MASKS__
//#define __BIT_MASK_PRACTICE__
//#define __BIT_MANIPULATION_PRACTICE__
//#define __NAMESPACES_AND_SCOPE__
//#define __LOCAL_VARIABLES__
//#define __GLOBAL_VARIABLES__
//#define __VARIABLE_SHADOWING__
//#define __INTERNAL_LINKAGE__
//#define __EXTERNAL_LINKAGE__
//#define __NON_CONST_GLOBALS_ARE_BAD__
//#define __INLINE_VARIABLES__
//#define __STATIC_LOCAL_VARIABLES__
//#define __SCOPE_DURATION_LINKAGE_SUMMARY__
//#define __INLINE_FUNCTIONS__
//#define __CONST_EXPR_EVAL__
//#define __S6_Quiz_Ex_One__
//#define __S6_Quiz_Ex_Two__
//#define __S6_Quiz_Ex_Three__
//#define __HANDLING_INVALID_INPUT__
//#define __PRNG__
//#define __S7_Quiz_Ex_One__
//#define __S7_Quiz_Ex_Two__
//#define __S7_Quiz_Ex_Three__
//#define __FUNCTION_TEMPLATES__
//#define __S8_Quiz_Ex_One__
//#define __S8_Quiz_Ex_Two__
//#define __S8_Quiz_Ex_Three_A__
//#define __S8_Quiz_Ex_Three_B__
//#define __S8_Quiz_Ex_Three_C__
//#define __S8_Quiz_Ex_Four__
//#define __S8_Quiz_Ex_Five_A__
//#define __S8_Quiz_Ex_Five_B__
#define __S8_Quiz_Ex_Five_C__
