#pragma once

//#include <iostream>

//#define __BASICS__
//#define __MULTIPLY_BY_TWO__
//#define __FUNCTIONS__
//#define __FORWARD_DECLARATIONS__
//#define __PRE_PROCESSOR_DIRECTIVES__
//#define __HEADER_GUARDS__
//#define __INTEGRAL_TYPES__
//#define __LITERALS__
//#define __CONSTANTS__
//#define __BIT_MANIPULATION__
//#define __BIT_WISE_OPERATORS__
//#define __BIT_MASKS__
//#define __BIT_MASK_PRACTICE__
//#define __BIT_MANIPULATION_PRACTICE__
//#define __NAMESPACES_AND_SCOPE__
//#define __LOCAL_VARIABLES__
//#define __GLOBAL_VARIABLES__
//#define __VARIABLE_SHADOWING__
//#define __INTERNAL_LINKAGE__
//#define __EXTERNAL_LINKAGE__
//#define __NON_CONST_GLOBALS_ARE_BAD__
//#define __INLINE_VARIABLES__
//#define __STATIC_LOCAL_VARIABLES__
//#define __SCOPE_DURATION_LINKAGE_SUMMARY__
//#define __INLINE_FUNCTIONS__
//#define __CONST_EXPR_EVAL__
//#define __S6_Quiz_Ex_One__
//#define __S6_Quiz_Ex_Two__
//#define __S6_Quiz_Ex_Three__
//#define __HANDLING_INVALID_INPUT__
//#define __PRNG__
//#define __S7_Quiz_Ex_One__
//#define __S7_Quiz_Ex_Two__
//#define __S7_Quiz_Ex_Three__
//#define __FUNCTION_TEMPLATES__
//#define __S8_Quiz_Ex_One__
//#define __S8_Quiz_Ex_Two__
//#define __S8_Quiz_Ex_Three_A__
//#define __S8_Quiz_Ex_Three_B__
//#define __S8_Quiz_Ex_Three_C__
//#define __S8_Quiz_Ex_Four__
//#define __S8_Quiz_Ex_Five_A__
//#define __S8_Quiz_Ex_Five_B__
//#define __S8_Quiz_Ex_Five_C__
//#define __S9_Quiz__
//#define __Unscoped_Enumerations__
//#define __Unscoped_Enumerations_IO__
//#define __Scoped_Enumerations__
//#define __S10_8_Quiz_Ex_One
//#define __S10_8_Quiz_Ex_Two
//#define __S10_8_Quiz_Ex_Three
//#define __S10_10_Class_Templates_1__
//#define __S10_Final_Quiz_1__
//#define __S10_Final_Quiz_3__
//#define __S11_2_Arrays__
//#define __S11_3_Arrays_and_Loops__
//#define __S11_4_Array_Sorting__
//#define __S11_4_STD_Sort__
//#define __S11_4_Quiz_Q1__
//#define __S11_4_Quiz_Q2__
//#define __S11_4_Quiz_Q3__
//#define __S11_4_Quiz_Q4__
//#define __S11_7_String_View_EX1__
//#define __S11_7_String_View_EX2__
//#define __S11_7_String_View_EX3__
//#define __S11_7_String_View_EX4__
//#define __S11_7_String_View_EX5__
//#define __S11_7_String_View_EX6__
//#define __S11_7_String_View_EX7__
//#define __S11_7_String_View_EX8__
//#define __S11_8_String_View_EX1__
#define __S11_8_String_View_EX2__
