#include <iostream>
#include <random>

#include "defineMain.h"

#ifdef __PRNG__
int main()
{
	// Initialize OS random device; this allows us to select random numbers from a pool of random numbers
	// already generated by the OS.
	std::random_device rd;

	// Get eight random integers from our random device to use as our seed
	std::seed_seq ss{rd(), rd(), rd(), rd(), rd(), rd(), rd(), rd()};

	// Initialize a Mersenne Twister with the seed_seq
	std::mt19937 mt{ss};

	// Create a reusable random number generator that generates uniform numbers between 1 and 6
	std::uniform_int_distribution die_6{1, 6};

	// Print some random numbers in rows of 10
	// Simulating the roll of a die
	for (int i = 1; i <= 40; ++i)
	{
		std::cout << die_6(mt) << '\t';

		if (i % 10 == 0)
		{
			std::cout << '\n';
		}
	}

	return 0;
}
#endif
